services:
  metrics:
    environment:
      NODE_MODE: archive
      NODE_SYNC: full
      NODE_DATABASE: rocksdb

  node:
    command:
      - node-subtensor
      - --chain
      - finney
      - --base-path
      - /tmp/blockchain
      - --bootnodes
      - /dns/bootnode.finney.chain.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC
      - --pruning
      - archive
      - --no-mdns
      - --rpc-external
      - --rpc-cors
      - all
      - --unsafe-rpc-external
      - --rpc-port
      - "9944"
      - --rpc-max-connections
      - "10000"
      - --database
      - rocksdb
      - --prometheus-external
      - --prometheus-port
      - "9615"
